from __future__ import annotations

from fabrid.domain.enums import (
    AttackFoldId,
    BotnetFamily,
    BudgetId,
    DecisionOperator,
    ExperimentalUnit,
    ExperimentVariantId,
    FallbackPolicy,
    OptimizationVariableKind,
    RetrainingPolicy,
    SolverBackend,
    ThresholdTiePolicy,
)
from fabrid.domain.identifiers import AttackSubtypeId
from fabrid.domain.values import (
    BatchSize,
    BudgetUsageRatio,
    DetectorSeed,
    DurationSeconds,
    EventRatePerClientHour,
    FalsePositiveBudget,
    FederatedRoundCount,
    LayerWidth,
    LearningRate,
    LocalEpochCount,
    PercentagePoints,
    Probability,
    RowCount,
    SolverGap,
)
from fabrid.protocol.alpha_grid import build_alpha_grid
from fabrid.protocol.models import (
    AttackFold,
    AttackFoldRotation,
    AttackSplitFraction,
    BenignSplitFractions,
    BotnetFamilyDirection,
    BotnetFamilySubtypes,
    BudgetComplianceGate,
    BudgetLevel,
    DetectorHyperparameters,
    DetectorProtocol,
    EventGate,
    EventGateSensitivity,
    FabridMacroGate,
    FabridMinimaxGate,
    FabridProtocol,
    GeneralizationProtocol,
    PracticalGates,
    ScoreContract,
    SolverSettings,
    StatisticsProtocol,
    UtilityEligibility,
)

PROTOCOL = FabridProtocol(
    score_contract=ScoreContract(
        decision_operator=DecisionOperator.STRICT_GREATER_THAN,
        tie_policy=ThresholdTiePolicy.NON_ALERT,
    ),
    detector=DetectorProtocol(
        seeds=tuple(DetectorSeed(seed) for seed in range(10)),
        retraining_policy=RetrainingPolicy.FROZEN_ACROSS_POLICIES,
        hyperparameters=DetectorHyperparameters(
            hidden_layers=(LayerWidth(64), LayerWidth(16)),
            learning_rate=LearningRate(0.001),
            local_epochs=LocalEpochCount(3),
            rounds=FederatedRoundCount(10),
            batch_size=BatchSize(64),
        ),
    ),
    alpha_grid=build_alpha_grid(),
    budgets=(
        BudgetLevel(
            BudgetId.FALSE_POSITIVE_0P001,
            FalsePositiveBudget(0.001),
        ),
        BudgetLevel(
            BudgetId.FALSE_POSITIVE_0P0025,
            FalsePositiveBudget(0.0025),
        ),
        BudgetLevel(
            BudgetId.FALSE_POSITIVE_0P005,
            FalsePositiveBudget(0.005),
        ),
        BudgetLevel(
            BudgetId.FALSE_POSITIVE_0P010,
            FalsePositiveBudget(0.010),
        ),
        BudgetLevel(
            BudgetId.FALSE_POSITIVE_0P020,
            FalsePositiveBudget(0.020),
        ),
    ),
    benign_splits=BenignSplitFractions(
        train_end=Probability(0.50),
        frontier_end=Probability(0.70),
        final_cal_end=Probability(0.80),
    ),
    attack_split=AttackSplitFraction(validation_end=Probability(0.20)),
    utility_eligibility=UtilityEligibility(
        minimum_attack_validation_rows=RowCount(200),
        minimum_eligible_subtypes=RowCount(2),
        minimum_rows_per_subtype=RowCount(50),
        fallback_policy=FallbackPolicy.EQUAL_FPR_AT_BUDGET,
    ),
    solver=SolverSettings(
        backend=SolverBackend.SCIPY_MILP,
        variable_kind=OptimizationVariableKind.BINARY,
        requested_gap=SolverGap(0.0),
        time_limit=DurationSeconds(300.0),
        accepted_gap=SolverGap(1.0e-5),
    ),
    statistics=StatisticsProtocol(
        experimental_unit=ExperimentalUnit.DETECTOR_SEED,
        sign_flip_enumeration=RowCount(1024),
        significance=Probability(0.05),
        holm_family_size=RowCount(5),
        bootstrap_resamples=RowCount(50_000),
        bootstrap_confidence=Probability(0.95),
    ),
    practical_gates=PracticalGates(
        fabrid_macro=FabridMacroGate(
            minimum_macro_recall_gain=PercentagePoints(2.0),
            minimum_passing_budgets=RowCount(3),
            total_budgets=RowCount(5),
        ),
        fabrid_minimax=FabridMinimaxGate(
            minimum_worst_client_recall_gain=PercentagePoints(5.0),
            maximum_macro_recall_loss=PercentagePoints(2.0),
            minimum_passing_budgets=RowCount(3),
            total_budgets=RowCount(5),
        ),
        budget_compliance=BudgetComplianceGate(
            maximum_median_usage=BudgetUsageRatio(1.05),
            seed_usage_limit=BudgetUsageRatio(1.10),
            minimum_seed_fraction_below_limit=Probability(0.9),
        ),
    ),
    generalization=GeneralizationProtocol(
        folds=(
            AttackFold(
                fold_id=AttackFoldId.FOLD_0,
                subtypes=(
                    AttackSubtypeId("bashlite_scan"),
                    AttackSubtypeId("bashlite_tcp"),
                    AttackSubtypeId("mirai_ack"),
                    AttackSubtypeId("mirai_udp"),
                ),
            ),
            AttackFold(
                fold_id=AttackFoldId.FOLD_1,
                subtypes=(
                    AttackSubtypeId("bashlite_junk"),
                    AttackSubtypeId("bashlite_udp"),
                    AttackSubtypeId("mirai_scan"),
                ),
            ),
            AttackFold(
                fold_id=AttackFoldId.FOLD_2,
                subtypes=(
                    AttackSubtypeId("bashlite_combo"),
                    AttackSubtypeId("mirai_syn"),
                    AttackSubtypeId("mirai_udpplain"),
                ),
            ),
        ),
        rotations=(
            AttackFoldRotation(
                variant_id=ExperimentVariantId.ATTACK_SUBTYPE_FOLD_0,
                validation_fold=AttackFoldId.FOLD_0,
                test_folds=(AttackFoldId.FOLD_1, AttackFoldId.FOLD_2),
            ),
            AttackFoldRotation(
                variant_id=ExperimentVariantId.ATTACK_SUBTYPE_FOLD_1,
                validation_fold=AttackFoldId.FOLD_1,
                test_folds=(AttackFoldId.FOLD_0, AttackFoldId.FOLD_2),
            ),
            AttackFoldRotation(
                variant_id=ExperimentVariantId.ATTACK_SUBTYPE_FOLD_2,
                validation_fold=AttackFoldId.FOLD_2,
                test_folds=(AttackFoldId.FOLD_0, AttackFoldId.FOLD_1),
            ),
        ),
        families=(
            BotnetFamilySubtypes(
                family=BotnetFamily.BASHLITE,
                subtypes=(
                    AttackSubtypeId("bashlite_scan"),
                    AttackSubtypeId("bashlite_junk"),
                    AttackSubtypeId("bashlite_udp"),
                    AttackSubtypeId("bashlite_tcp"),
                    AttackSubtypeId("bashlite_combo"),
                ),
            ),
            BotnetFamilySubtypes(
                family=BotnetFamily.MIRAI,
                subtypes=(
                    AttackSubtypeId("mirai_scan"),
                    AttackSubtypeId("mirai_ack"),
                    AttackSubtypeId("mirai_syn"),
                    AttackSubtypeId("mirai_udp"),
                    AttackSubtypeId("mirai_udpplain"),
                ),
            ),
        ),
        family_directions=(
            BotnetFamilyDirection(
                variant_id=ExperimentVariantId.BOTNET_BASHLITE_TO_MIRAI,
                validation_family=BotnetFamily.BASHLITE,
                test_family=BotnetFamily.MIRAI,
            ),
            BotnetFamilyDirection(
                variant_id=ExperimentVariantId.BOTNET_MIRAI_TO_BASHLITE,
                validation_family=BotnetFamily.MIRAI,
                test_family=BotnetFamily.BASHLITE,
            ),
        ),
        botnet_eligible_client_count=RowCount(7),
    ),
    allocation_sensitivity_replicates=RowCount(500),
    conservative_utility_confidence=Probability(0.95),
    event_gate=EventGate(
        dilation=DurationSeconds(2.0),
        merge_gap=DurationSeconds(5.0),
        minimum_event_length=DurationSeconds(2.0),
        cooldown=DurationSeconds(10.0),
        maximum_alarm_duty=Probability(0.25),
        budgets_per_client_hour=tuple(
            EventRatePerClientHour(value) for value in (0.1, 0.2, 0.5)
        ),
        sensitivity=EventGateSensitivity(
            dilation=tuple(DurationSeconds(value) for value in (1.0, 2.0, 3.0)),
            merge_gap=tuple(DurationSeconds(value) for value in (3.0, 5.0, 10.0)),
            minimum_event_length=tuple(
                DurationSeconds(value) for value in (1.0, 2.0, 3.0)
            ),
            cooldown=tuple(DurationSeconds(value) for value in (5.0, 10.0, 20.0)),
        ),
    ),
)
